### ISSUE TITLE
Can we use this feature for testing of whitelist API or REST API or Custom API

### ISSUE THREAD

**Issue by sumitjain236** [ElasticRun/barista#2]

**Comment by karthiksasi** [comment]
Yes. Test Case can be created with Test Case Type as **Function**
<img width="1306" alt="Screenshot 2022-10-14 at 9 57 57 AM" src="https://user-images.githubusercontent.com/48323876/195762514-241efcb0-122d-4eab-abd5-12eab513b80f.png">

**Comment by sumitjain236** [comment]
Thank You
